import {defineConfig, loadEnv} from "vite"

const buildDate = new Date()
const appVersionDate = [
  buildDate.getUTCFullYear(),
  String(buildDate.getUTCMonth() + 1).padStart(2, "0"),
  String(buildDate.getUTCDate()).padStart(2, "0"),
].join("")

const injectAppVersionDate = () => ({
  name: "inject-app-version-date",
  transformIndexHtml: html => html.replaceAll("%APP_VERSION_DATE%", appVersionDate),
})

export default defineConfig(({mode}) => {
  const env = loadEnv(mode, ".", "")

  // Vercel preview deploys serve the app at the root of an autogenerated
  // subdomain (e.g. rfs-v2-hydroviewer-<hash>.vercel.app/), not at the
  // production subpath (/hydroviewer/). Honoring VITE_BASE_PATH
  // unconditionally would emit asset URLs prefixed with /hydroviewer/ on a
  // host that serves them at /, producing 404s. Force base to / for any
  // non-production Vercel environment regardless of how env vars are
  // configured.
  const isVercelNonProd =
    env.VERCEL === "1" && env.VERCEL_ENV !== "production"

  return {
    base: isVercelNonProd ? "/" : env.VITE_BASE_PATH || "/",
    plugins: [injectAppVersionDate()],
    worker: {
      format: "es", // Use ES modules in workers
    },
    build: {
      target: "esnext",
    },
    define: {
      global: "globalThis",
    },
  }
})
